name: update-sources
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  update-sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: ./update
      - run: "git config user.email vdesjardins@users.noreply.github.com"
      - run: "git config user.name terraform-overlay"
      - run: "git add -A"
      - run: "git commit -m 'update sources.json' | true"
      - run: "git push -u origin main"
